/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ziv_threads_LibraryAPI */

#ifndef _Included_com_ziv_threads_LibraryAPI
#define _Included_com_ziv_threads_LibraryAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ziv_threads_LibraryAPI
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ziv_threads_LibraryAPI_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_ziv_threads_LibraryAPI
 * Method:    nativeFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ziv_threads_LibraryAPI_nativeFree
  (JNIEnv *, jobject);

/*
 * Class:     com_ziv_threads_LibraryAPI
 * Method:    nativeWorker
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_ziv_threads_LibraryAPI_nativeWorker
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ziv_threads_LibraryAPI
 * Method:    posixThreads
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_ziv_threads_LibraryAPI_posixThreads
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
